Add shellsheck compliance

diff --git a/image/pingo b/image/pingo
--- a/image/pingo
+++ b/image/pingo
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck disable=SC2086
 
 # pingo - POSIX-compliant shell script to help running pingo through Wine
 #
@@ -16,6 +17,15 @@
 pingo_dir='/usr/share/pingo'
 pingo_file='pingo.exe'
 
+# cd_error function: print a message indicating a failed cd command and exit
+# arguments: $1 - the directory that failed to cd into
+# return value: none
+# return code (status): not relevant, will exit the program
+cd_error() {
+    printf '%s\n' "error: could not cd into '${1%/}/' directory" >&2
+    exit 1
+}
+
 # check if requirements are installed (wine and pingo.exe)
 command -v wine >/dev/null 2>&1 ||
 {
@@ -26,7 +36,7 @@ command -v wine >/dev/null 2>&1 ||
 test -f "${pingo_dir}/${pingo_file}" ||
 {
     printf '%s\n' "error: '${pingo_file}' not found"        >&2;
-    printf '%s\n' "       please copy it to '${pingo_dir}'" >&2;
+    printf '%s\n' "       please copy it to '${pingo_dir}/'" >&2;
     exit 1;
 }
 
@@ -40,8 +50,8 @@ do
     if [ -f "$arg" ] 
     then
         # map path for wine using default WINEPREFIX
-        filepath="$(printf '%s' "$(cd "$(dirname "$arg")"; pwd)/$(basename "$arg")")"
-        imgfiles="${imgfiles} ${HOME}"/.wine/dosdevices/z\:"$filepath"
+        fullpath="$(printf '%s' "$(cd "$(dirname "$arg")" || cd_error "$(dirname "$arg")"; pwd)/$(basename "$arg")")"
+        imgfiles="${imgfiles} ${HOME}"/.wine/dosdevices/z\:"$fullpath"
     else
         # if not a valid file, just store it (should be an option)
         pingo_opts="${pingo_opts} ${arg}"
@@ -53,5 +63,5 @@ done
  pingo_opts="$(printf '%s' "$pingo_opts" | sed 's/.//')"
 
 # execute pingo through wine
-cd "$pingo_dir"
+cd "$pingo_dir" || cd_error "$pingo_dir"
 wine ./"$pingo_file" $pingo_opts $imgfiles
diff --git a/image/truepng b/image/truepng
--- a/image/truepng
+++ b/image/truepng
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck disable=SC2086
 
 # truepng - POSIX-compliant shell script to help running TruePNG through Wine
 #
@@ -16,6 +17,15 @@
 truepng_dir='/usr/share/truepng'
 truepng_file='TruePNG.exe'
 
+# cd_error function: print a message indicating a failed cd command and exit
+# arguments: $1 - the directory that failed to cd into
+# return value: none
+# return code (status): not relevant, will exit the program
+cd_error() {
+    printf '%s\n' "error: could not cd into '${1%/}/' directory" >&2
+    exit 1
+}
+
 # check if requirements are installed (wine and TruePNG.exe)
 command -v wine >/dev/null 2>&1 ||
 {
@@ -26,7 +36,7 @@ command -v wine >/dev/null 2>&1 ||
 test -f "${truepng_dir}/${truepng_file}" ||
 {
     printf '%s\n' "error: '${truepng_file}' not found"        >&2;
-    printf '%s\n' "       please copy it to '${truepng_dir}'" >&2;
+    printf '%s\n' "       please copy it to '${truepng_dir}/'" >&2;
     exit 1;
 }
 
@@ -40,8 +50,8 @@ do
     if [ -f "$arg" ] 
     then
         # map path for wine using default WINEPREFIX
-        filepath="$(printf '%s' "$(cd "$(dirname "$arg")"; pwd)/$(basename "$arg")")"
-        pngfiles="${pngfiles} ${HOME}"/.wine/dosdevices/z\:"$filepath"
+        fullpath="$(printf '%s' "$(cd "$(dirname "$arg")" || cd_error "$(dirname "$arg")"; pwd)/$(basename "$arg")")"
+        pngfiles="${pngfiles} ${HOME}"/.wine/dosdevices/z\:"$fullpath"
     else
         # if not a valid file, just store it (should be an option)
         truepng_opts="${truepng_opts} ${arg}"
@@ -53,5 +63,5 @@ done
  truepng_opts="$(printf '%s' "$truepng_opts" | sed 's/.//')"
 
 # execute TruePNG through wine
-cd "$truepng_dir"
+cd "$truepng_dir" || cd_error "$truepng_dir"
 wine ./"$truepng_file" $truepng_opts $pngfiles
